version: 2

project_name: overthink

before:
  hooks:
    - go mod tidy

builds:
  - id: overthink
    main: ./cmd/overthink
    binary: overthink
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: overthink
    builds:
      - overthink
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: rishichawda
    name: overthinker

brews:
  - name: overthink
    ids:
      - overthink
    repository:
      owner: rishichawda
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/rishichawda/overthinker"
    description: "A dramatic overanalysis engine for your most questionable life decisions"
    license: "MIT"
    skip_upload: auto
    test: |
      assert_match "overthink -- a dramatic overanalysis engine", shell_output("#{bin}/overthink 2>&1", 1)
    install: |
      bin.install "overthink"
